### ISSUE TITLE
Incorporate continuous integration 

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#1]
@tdhock Shinytest can be used with Travis, so I'll plan to set that up once I have some tests.

**Comment by tdhock** [comment]
so can RSelenium, I used that with https://github.com/tdhock/animint2 and https://github.com/tdhock/animint

**Comment by julianstanley** [comment]
Setup travis and `testthat` with `golem`/`usethis` as part of #5. First commit to build successfully is e1fd2127f5ecbe766d08fb8e70169a7cfe5e51d5.

**Comment by julianstanley** [comment]
Okay, now codecov is setup via #9. So, to close this issue, I just need to:

* write some basic RSelenium and shinytest tests (#7)
* get travis to run those tests

And then I can close this issue and #7. 

Anything else that I'm missing @tdhock?

**Comment by tdhock** [comment]
sounds good
