### ISSUE TITLE
Setup continuous deployment to shinyapps.io

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#10]
@tdhock 

One of my big goals is to have a _minimally functional_ application up-and-running ASAP, and then keep the app functional as I build up features.

This fits with deploying the app to a free-tier shinyapps.io in Phase 1 and continuously re-deploying from travis.

It looks like doing that will be super straightforward, thanks to a [tutorial from Jarret Meyer](https://jarrettmeyer.com/2019/04/25/publishing-to-shinyapps-github-travis-ci).

**Comment by tdhock** [comment]
sounds good to me
minimally functional is I guess running GFPOP and showing some standard data viz
