### ISSUE TITLE
Think carefully about how to best modularize code

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#12]
I initially tried designing modules for each page in the app. I knew that that wasn't best practice, but I wanted some modularization. 

In #11 I ended up deleting the code from those modules and just putting them in the main UI and server functions because the "Welcome" and "Analysis" pages needed to communicate with each other, and modules should be independent.

So I'm going to read https://mastering-shiny.org/scaling-modules.html more carefully and learn more about it applies to this project.

**Comment by julianstanley** [comment]
@tdhock 

I thought that the way that I just sourced tabs previously (like [here in a previous repo](https://github.com/ApfeldLab/SensorOverlord/blob/master/inst/shinyApp/app.R)) wasn't best practice, which is why I was trying to refactor things.

But I think it actually is, judging from shiny expert daattali using the same pattern [a few years ago in his ddpcr app](https://github.com/daattali/ddpcr/blob/master/inst/shiny/ui.R).

So that's one of the improvements I'm going to make today in the clean-up-shell branch.

**Comment by tdhock** [comment]
I'm not a shiny expert so I can't advise on best practices for shiny in particular, but in general is is always a good idea to write modular code with abstractions that let you avoid repetition. If you are using daatali's code I would recommend asking him about ideas /feedback.
