### ISSUE TITLE
gfpop does not accept custom graphs

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#18]
@tdhock 

EDIT: I fixed this before figuring out the problem (and will close this issue once it's merged), but I'm going to post it anyways for documentation/history purposes.

I fell for a typical blunder: when I ran `read.csv`, I needed to set `stringsAsFactors = FALSE`. After that (and a few other little changes: for example, dropping all columns that don't have a header name that gfpop::graph recognizes) things seem to be working dandily.

-----------------------------------
Original issue:

I'm having trouble with getting `gfpop` to accept a user-uploaded graph.

I generated a graph with `gfpop::graph`, which works with `gfpop`. Then, when I export that graph to csv and then re-import the graph, `gfpop` does not recognize it.

Passing the imported csv to `gfpop::graph` works, but leads to a different error when I try to run gfpop ("replacement has length zero.")

I'll put a portable snippet below. Does this look like an error in `gfpop`, or am I doing something wrong?

```{r}
# Create a working graph
iso_graph <- gfpop::graph(penalty = 15, type = "isotonic")
gfpop::gfpop(data = gfpop_data$primary_input$Y, mygraph = iso_graph, type = "mean")$changepoints
# [1]  499 1000

# Export and re-import the working graph
write.csv(iso_graph, "graphtest.csv", row.names = FALSE)
iso_graph_import <- read.csv("graphtest.csv")

# Attempt: imported graph
gfpop::gfpop(data = gfpop_data$primary_input$Y, mygraph = iso_graph_import, type = "mean")$changepoints
# Error: Error in gfpop::gfpop(data = gfpop_data$primary_input$Y, mygraph = iso_graph_import,  : 
# Your graph is not a graph created with the graph function of the gfpop package.

# Attempt 2: imported graph passed through gfpop::graph
iso_graph_import_2 <- gfpop::graph(iso_graph_import)
gfpop::gfpop(data = gfpop_data$primary_input$Y, mygraph = iso_graph_import_2, type = "mean")$changepoints
# Error: Error in x[[jj]][iseq] <- vjj : replacement has length zero

# Attempt 3: Maybe the NAs are causing trouble?
iso_graph_import_3 <- iso_graph_import_2 %>% dplyr::select_if(~ !any(is.na(.)))
gfpop::gfpop(data = gfpop_data$primary_input$Y, mygraph = iso_graph_import_3, type = "mean")$changepoints
# Error: Error in x[[jj]][iseq] <- vjj : replacement has length zero
```

**Comment by tdhock** [comment]
you may want to post an issue on https://github.com/vrunge/gfpop about a more informative error message
