### ISSUE TITLE
Decide on an appropriate framework for constraint graph

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#2]
@tdhock

Candidates:

- visNetwork
- plotly (e.g. shinyDAG)

Moving forward:
(a) playing with my forked version of visNetwork to see if I can get it to match our specifications, and
(b) playing with shinyDAG's plotly graph implementation to see if that would end up being easier.

# visNetwork

There are two obstacles to using visNetwork: (1) I'll need to make edits to visNetwork's core javascript file (for example, allowing edge labels to be updated and having more input parameters for edges/nodes), and (2) I don't think visNetwork can easily interface with plotly (for the "hover over changepoint-->highlight associated node" feature). If I just had two plotly graphs, then I could use `crosstalk`, but visNetwork doesn't support crosstalk just yet.

## Interactions with visNetwork

I created [issue 337 in visNetwork](https://github.com/datastorm-open/visNetwork/issues/377) asking about the two obstacles expressed above.

I previously thought that saving the network visualization (after the user edits it) would be a problem, based on [issue 356](https://github.com/datastorm-open/visNetwork/issues/356). But I found a [StackOverflow post addressing that](https://stackoverflow.com/questions/54846529/how-to-extract-and-save-visnetwork-manipulation-changes-in-shiny) which I added as comment on that issue.

Issue #2 (making visNetwork interface with other plots) was already brought up with visNetwork about two years ago when a user asked about `crosstalk` integration. At the time, the repo maintainer seems to have tried to implement that integration unsuccessfully. I asked about that in [the crosstalk issue, number 229](https://github.com/datastorm-open/visNetwork/issues/229).

# plotly

If I go down this route, looking at [shinyDAG](https://github.com/GerkeLab/ShinyDAG) may be a good option.

**Comment by julianstanley** [comment]
From @tdhock in email: I asked about whether it's appropriate to fork `visNetwork` and just have the shiny app rely on the forked version (since I think the issues raised above might be too specific to our application). Response:

> 1. best option: visNetwork maintainers think your feature is great and will consider merging a PR and maintaining that feature in their repo. did you ask the visNetwork maintainers if they are interested in supporting the features you need? Is it within scope of their package goals?
> 2. not as good: if visNetwork maintainers dont want to maintain your feature then you would need to either
> A) fork their repo and then make it work / maintain it yourself, or
> B) start from scratch and implement it yourself (without building on visnetwork)

**Comment by julianstanley** [comment]
Update: I posed this question as [a post in the Rstudio community forum](https://community.rstudio.com/t/which-tool-is-best-for-interactive-editable-linked-directed-graphs/67315). Hopefully someone on there will have helpful advice!

**Comment by julianstanley** [comment]
[pieterjanvc's comment](https://community.rstudio.com/t/which-tool-is-appropriate-for-interactive-editable-linked-directed-graphs/67315/2) on the Rstudio community post was really helpful.

They essentially say to, for now, just use what visNetwork already has to offer. Then, write an interface to edit edges separately from the visNetwork window. When a user selects an edge, I can capture the edge ID and use that to link the selection with a dataframe. Then I can display info from that dataframe and allow the user to edit that info. I can also use that ID to highlight parts of the plotly graph.

That solution will require some server-side computations, unfortunately, but pieterjanvc thinks that it shouldn't be too bad.

**Comment by tdhock** [comment]
that is good to know about as an option for an indirect manipulation interface (editing takes place away from the object being manipulated -- the edge). Too bad there is no straightforward direct manipulation option (pop up and edit right on top of / next to the edge).
Also too bad for hitting the server. Ideally we would only hit the server when we want to run gfpop::gfpop with new data/parameters.

**Comment by julianstanley** [comment]
[bthieurmel's recent improvements to visNetwork](https://github.com/datastorm-open/visNetwork/issues/377) have been super helpful to getting us closer to a solution.

Now, we can _basically_ do everything, it's just not as convenient as ideal.

I made a quick testapp to show where we're at. [I put the source in a gist here](https://gist.github.com/julianstanley/74321b6b75584e9e17cd68666b2177c2).

That app can now hold all of the edge parameters that we need! My quick prototype isn't pretty, but it works:

![image](https://user-images.githubusercontent.com/22749289/83308255-6d78e680-a1d4-11ea-8384-d1653300c814.png) 

You can also edit the edge, but that's where there's a bit of an inconvenience: as I documented in [visNetwork issue 337](https://github.com/datastorm-open/visNetwork/issues/377), non-standard parameters don't show up in the edit boxes.

So, that means, when you edit an edge, you need to re-input _all_ nonstandard parameters, even if you just want to change one:

![image](https://user-images.githubusercontent.com/22749289/83308358-aadd7400-a1d4-11ea-847e-a35715d50f70.png)

But, as long as you do that, the graph changes appropriately. As an example, I'll increase this edge's penalty to 50:

![image](https://user-images.githubusercontent.com/22749289/83308475-d3fe0480-a1d4-11ea-8adc-bcc499c53ad7.png)

## Moving forward

* Would be nice to have a dropdown box for "type", but I'm not sure that's going to be feasible.
* It sucks to have to re-enter edge values. Hopefully, I'm making a mistake with that because, after spending an hour or so trying to debug visNetwork to figure out why that happens, I still don't have any idea. I'll look at it again later, but hopefully, bthieurmel knows/has a hunch.

**Comment by tdhock** [comment]
great progress, thanks for the update. really cool that visNetwork dev is on board.

**Comment by tdhock** [comment]
when it does start working (or maybe even now) it would be a good idea to write a simple test which uses the new functionality, and send a PR to visNetwork (need to check what test framework they use), to make it easier for them to know in the future whether or not they are breaking the functionality that we depend on. if it is too complicated to create the test yourself, maybe ask the visNetwork dev how to do it / if he can write the test himself.

**Comment by julianstanley** [comment]
@tdhock That's a great idea, but I think that visNetwork has great examples, but no formal/automated tests (at least not on GitHub). I was looking for them earlier today, since I wasn't sure how to test visNetwork output (vdiffr doesn't work on dynamic plots, and I don't see an option to convert visNetworks to static plots--which I think is how plotly got around that). 

visNetwork has one test folder, in "inst/test", but they look like informal tests--basically just examples.

**Comment by julianstanley** [comment]
This is all set now--visNetwork did everything that we needed for an interactive graph, except for `crosstalk` support.
