### ISSUE TITLE
Some weirdness with the deployed shinyapp

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#20]
@tdhock 

Somewhat low priority:

Custom graphs (specifically: the datatable on the 'home' page showing the graph) are working on my local version, but not the shinyapp deployed version.

I think this might be because my travis.yml caches R packages. This repo itself (`julianstanley/gfpop-gui`) is also a travis R package dependency. So the weirdness might be because of the cache? So then, just re-installing gfpop-gui from the deploy script _should_ do the trick.

So this is just a reminder to myself to look into that more, and maybe make a branch with that modified script and see if that helps.

**Comment by tdhock** [comment]
i'm not sure

**Comment by julianstanley** [comment]
Yeah, re-deploying my local copy seems to do have done the trick for this and also resolves #21 

So, I'll open a new issue to debug the continuous shinyapps.io deployment sometime in the future. The travis logs say that it deploys successfully, but that's obviously not the case.
