### ISSUE TITLE
Setup a testing framework

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpop-gui#7]
@tdhock 

RSelenium has a [vignette dedicated to testing shiny apps](https://cran.r-project.org/web/packages/RSelenium/vignettes/shinytesting.html). I'm not sure about the relationship between [shinytest](https://rstudio.github.io/shinytest/articles/shinytest.html) and RSelenium yet, so I'm going to do more reading on those. I'll likely end up using both.

As mentioned in #1, RSelenium can also be integrated with Travis. 

I added some very basic tests in #6 through testthat. In the near-term, I should play around with writing some very basic tests with shinytest and RSelenium to get a feel for that and make sure I can get Travis to run them.

To have _something_ to test at least, I should go ahead and design a home page based on the sketches in #3. I'll make a separate issue for that (#8)

**Comment by tdhock** [comment]
any idea what kinds of features you would test with shinytest vs RSelenium? I have not really used shinytest and it seems to be doing more or less the same thing as RSelenium? shinytest is maybe a bit more like unit testing whereas RSelenium is a bit more like integration testing?

**Comment by julianstanley** [comment]
> any idea what kinds of features you would test with shinytest vs RSelenium? I have not really used shinytest and it seems to be doing more or less the same thing as RSelenium? shinytest is maybe a bit more like unit testing whereas RSelenium is a bit more like integration testing?

I'm not sure yet. In fact, I might just start with `shinytest` and use RSelenium only as-needed.

`shinytest` runs a set of scripted interactions with the full app and then takes snapshots of the application state. So, in that sense, it should be able to do full-fledged integration testing of interactions with the graph, plot, etc.

[one article about shiny testing](https://appsilon.com/super-solutions-for-shiny-architecture-5-automated-tests/) says:
>It [RSelenium] is harder to configure than _shinytest_, but it does the job. [...] I guess the best strategy would be to start with _shinytest_ and if there are some problems with using it, switch to some other more general solution for web applications.

But I really need to be more specific here. For example: what's the best way to test whether, when the user clicks the "run gfpop" button, gfpop is actually run successfully?

I'm going to read about this more and give a better answer by end-of-day Wednesday. 

[bot] /remind me to post a testing update Wednesday at 14:00

**Comment by julianstanley** [comment]
/remind me to post a testing update Wednesday at 14:00

**Comment by tdhock** [comment]
I think Rselenium would be the only option if you wanted to test for client-side interactions, such as "hovering over this edge in the node/edge graph display should highlight the corresponding changepoint in the data plot" (I don't think shinytest can do that, maybe I'm wrong though)

**Comment by julianstanley** [comment]
Okay--so, progress on this!

I think shinytest can do more now than it used to. So, for example, shinytest _was_ able to detect when I changed tooltip information in plotly. It's able to detect changes like that as of [this merge in early 2019](https://github.com/rstudio/shinytest/pull/232), which allows shinytest to grab the JSON data that binds to plotly (which includes the tooltip info and X/Y location of *every* plotly point, which is phenomenal).

So, an example of something I could test with `shinytest` really easily: are the tooltips in the plotly plot accurate? Does pressing the "generate data" button actually generate data? Is that data displayed in the table on the home page? If I press the button to generate a updown graph with a penalty of 12 and run gfpop on a set of generated data with a set seed, are the changepoints self-consistent? Etc. So, I think we can get a lot of goodness out of that.

But, I think that you are 100% right that shinytest is not able to test client-side interactions. Just in case, I posted [an issue in shinytest](https://github.com/rstudio/shinytest/issues/312) asking about a super simple case: testing whether the user can pan over a plotly graph.

So, examples of things to test with RSelenium: everything else (e.g. client-side interactions/highlighting)

TODO:
- [ ] Write a few more shinytest tests and push progress (super quick)
- [ ] Work on getting RSelenium setup (will probably take a while)

**Comment by julianstanley** [comment]
More updates on this:

- `shinytest` isn't actually working as well as I'd hope. It keeps crashing on relatively simple tests. I think it's related to [this shinytest issue](https://github.com/rstudio/shinytest/issues/192), which seems to be linked to certain plotly inputs? I troubleshoot this a lot today, but wasn't able to get it to work.

- I've at least gotten RSelenium somewhat working as of the end of today. They recently updated to recommend driving the server through dockers, so I set that up. Then, I was getting [this error](https://stackoverflow.com/questions/45850278/rselenium-cant-connect-to-running-shiny-app), where I could connect to remote URLs but not localhost. The accepted/top answer there seemed pretty involved but jdharrison's answer worked great. So I don't forget, here's the process to get RSelenium up and running on a shiny app:

```r
# After installing docker and configuring it to run without sudo
system("docker run -d --net=host selenium/standalone-chrome&")

# Load up RSelenium
library(RSelenium) 
remDr <- remoteDriver(remoteServerAddr = "localhost", port = 4444, browser = "chrome") 
remDr$open()

# Load up app
options(shiny.port = 11616)
gfpopgui::run_app()

# Confirm that app is running
remDr$navigate(url = "http://127.0.0.1:6100/")
remDr$getTitle()[[1]]
> [1] "gfpopgui"
```

**Comment by julianstanley** [comment]
@tdhock 

So, I finally got a [travis build to pass with an RSelenium test](https://travis-ci.com/github/julianstanley/gfpop-gui/jobs/342643699), but there's an error in the build that I thought I should ask about.

Basically: my tests work locally. I have to:

(1) start up a selenium server on docker, making sure to include `--net=host`,
(2) start up my shiny app in the background
(3) test

So, I did the same thing on travis:

(1) enabled `services: docker` and ran docker like I do locally `before_install`.
(2) This is a bit hacky--but I startup my shiny app in the background as a `system` command in `testthat.R`: `system("${R_HOME}/bin/Rscript -e 'golem::detach_all_attached();golem::document_and_reload();options(shiny.port = 11616);run_app()' &")`. Is there a better way I should be doing this?
(3) And then tests are run with the R CMD check

So, this time around, my build exited successfully:

```
# (Travis log line 1424-1425)
  Running ‘testthat.R’
 OK
```

Cool, cool. But then the same tests weirdly fail in the `after_success` part, when running covr::codecov()

```
11.75s$ Rscript -e 'covr::codecov()'
Error: Failure in `/tmp/Rtmp3t68dd/R_LIBS3e385ae0775e/gfpopgui/gfpopgui-tests/testthat.Rout.fail`
o")) : menu() cannot be used non-interactively
── Error documenting your package ──────────────────────────────────────────────
Error in run_app() : could not find function "run_app"
Execution halted
> 
> test_check("gfpopgui")
── 1. Failure: can connect to app (@test-app-basic.R#12)  ──────────────────────
`appTitle` not equal to "gfpopgui".
1/1 mismatches
x[1]: ""
y[1]: "gfpopgui"
══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 0 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: can connect to app (@test-app-basic.R#12) 
Error: testthat unit tests failed
Execution halted
Execution halted
```

So, I guess `covr` also runs the tests independently? And, in that case, the test failed? I'm tempted to ignore that since the build succeeded, but I feel like it might point at a problem that will come back to bite later.

**Comment by tdhock** [comment]
great to hear that you got a first RSelenium test passing. that will be really useful going forward.
about covr I'm not sure because I don't think I have ever used code coverage and RSelenium/travis in the same project.
it is a good idea to do code coverage if you can, and i'm sure you're not the first person to try using covr+shiny, so you may consider looking at issues https://github.com/r-lib/covr/issues?q=shiny and then posting one there if you don't see anything relevant.
